version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: payment-service-sqlserver-dev
    restart: unless-stopped
    environment:
      SA_PASSWORD: SqlServer_Dev_Pass123!
      ACCEPT_EULA: 'Y'
      MSSQL_PID: 'Express'
    ports:
      - '1434:1433' # Use different port to avoid conflicts
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./database/scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - aioutlet-network
    healthcheck:
      test: ['CMD-SHELL', "timeout 10s bash -c '</dev/tcp/localhost/1433'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-service-dev
    restart: unless-stopped
    ports:
      - '8084:80' # Consistent port pattern
      - '8085:443'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=PaymentServiceDb_Dev;User Id=sa;Password=SqlServer_Dev_Pass123!;TrustServerCertificate=True;
      - RabbitMQ__ConnectionString=amqp://admin:admin123@aioutlet-rabbitmq:5672/
      - JWT__Secret=payment-service-jwt-secret-development
      - JWT__Issuer=aioutlet-auth-service
      - JWT__Audience=aioutlet-payment-service
      - PaymentGateway__ApiKey=dev_api_key
      - PaymentGateway__SecretKey=dev_secret_key
      - ServiceDiscovery__OrderServiceUrl=http://order-service-dev:80
      - ServiceDiscovery__NotificationServiceUrl=http://notification-service-dev:80
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    networks:
      - aioutlet-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  sqlserver_data:
    driver: local

networks:
  aioutlet-network:
    external: true
